__author__ = "alvaro barbeira"

ID="id"
EFFECT_ALLELE="effect_allele"
NON_EFFECT_ALLELE="non_effect_allele"
ZSCORE="zscore"
CHROMOSOME = "chromosome"
POSITION = "position"
DOSAGES="dosages"
FREQUENCY="frequency"
OR="or"
BETA="effect_size"
BETA_SIGN="beta_sign"
SE="standard_error"
PVALUE="pvalue"

GENE="gene"
GENE_NAME="gene_name"